[features]
seeds = false
skip-lint = false
[programs.localnet]
# presale = "HCXo1ZoY2ALW9dWDBjU1NfwHoaEEDsZ9g1FwrNfRC7GC"
presale = "7y5yBiJ1Jv4dotxMciA4YKT2cE5oYLigtuwkhP1rXRJs"
[programs.devnet]
presale = "7y5yBiJ1Jv4dotxMciA4YKT2cE5oYLigtuwkhP1rXRJs"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "http://127.0.0.1:8899"
# wallet = "~/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
