[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfunding = "57gCHHkhU7GdkXx1DybsMEkCGEULC2ojx7wr5bykKaeV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
