[workspace]
resolver = "2"
members = ["programs/*"]

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
