[toolchain]

[features]
resolution = true
skip-lint = false

#when deploy on devnet change the localnet into devnet
[programs.devnet]
gifportal = "AsJfSnJ1TVRw5CNcC7StpBWNdiz7krfMxFyMaQGWjKnz"

[registry]
url = "https://api.apr.dev"

#when deploy on devnet change the localnet into devnet in the cluster
[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
